steps:
  # 1. Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gtech-crm-backend:latest', './backend']
    id: Build-Backend

  # 2. Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gtech-crm-frontend:latest', './frontend']
    id: Build-Frontend

  # 3. Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gtech-crm-backend:latest']
    id: Push-Backend

  # 4. Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gtech-crm-frontend:latest']
    id: Push-Frontend

  # 5. Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gtech-crm-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gtech-crm-backend:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:gtech-crm-db'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://postgres:gtech2026@localhost/postgres?host=/cloudsql/$PROJECT_ID:us-central1:gtech-crm-db,JWT_SECRET=$$JWT_SECRET'
    secretEnv: ['JWT_SECRET']
    id: Deploy-Backend

  # 6. Deploy Frontend to Cloud Run (linked to Backend)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Getting Backend URL..."
        BACKEND_URL=$(gcloud run services describe gtech-crm-backend --platform managed --region us-central1 --format 'value(status.url)')
        echo "Backend URL: $$BACKEND_URL"
        
        echo "Deploying Frontend..."
        gcloud run deploy gtech-crm-frontend \
          --image gcr.io/$PROJECT_ID/gtech-crm-frontend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars BACKEND_URL=$$BACKEND_URL \
          --port 8080
    id: Deploy-Frontend

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
    env: 'JWT_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY